### ISSUE TITLE
Support M1 MacBooks 

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/local#132]
**Is your feature request related to a problem? Please describe.**

New MacBooks use M1 chips, this environment should seamlessly work on these systems.

**Comment by jeremyw24** [comment]
Error:
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/4019090/182976576-91ad77b8-e254-4c4a-badc-aec7e0aac33e.png">

**Comment by viv-4** [comment]
Init appears to be hanging at this stage of the secret generation: 
https://github.com/PlaceOS/init/blob/d671e23e4d0d8fc2b889ca7dc2618ee49cd052ee/scripts/generate-secrets#L113

Which uses the Sodium shard to generate a key:
https://github.com/PlaceOS/init/blob/8c24039c05000b804e1ec81a73644fa625d1fcdf/src/tasks/secrets.cr#L8

**Comment by stakach** [comment]
looks like that's the only place it's used too, I'll see if we can remove the dependency

**Comment by stakach** [comment]
@viv-4 or @jeremyw24 can you test again on Apple silicone after installing the required lib:

`brew install libsodium`

**Comment by stakach** [comment]
Actually I looked into that method on libsodium and I actually already wrote pure crystal version of that exact algorithm 9 days ago, what luck
https://github.com/spider-gazelle/ed25519

**Comment by stakach** [comment]
Also this is what lib sodium was used for: `Random::Secure.hex(32).hexbytes`
all that is actually required to generate a ed25519 private key

**Comment by viv-4** [comment]
Also verified still working on x86_64 Ubuntu 20.04
