### ISSUE TITLE
Use `shellspec` to unit test `placeos` script

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/local#98]
**Is your feature request related to a problem? Please describe.**

Bugs can pop-up anywhere code is written, bash scripts are no exception.
Unit testing can always help tease out bugs/sure up behaviour of a script

**Describe the solution you'd like**

Use [shellspec](https://github.com/shellspec/shellspec) to unit test expected behaviours.

**Describe alternatives you've considered**

e2e runs of the `partner-environment` to validate everything works.

**Comment by w-le** [comment]
An excellent standalone task to get @rdiazx familiar with GitHub actions for automated testing and with partner-environment and the PlaceOS rest API and init container and scripts

**Comment by caspiano** [comment]
Closing as most functionality is tested via GitHub actions and attention should be placed elsewhere
